version: '3.9'
services:
  backend-flexyte:
    container_name: backend-flexyte
    image: ghcr.io/florentkaram/backend-flexyte/backend-flexyte:latest
    restart: unless-stopped
    command: npm run start:prod
    labels:
      traefik.enable: true
      traefik.http.routers.backend-flexyte.entrypoints: websecure
      traefik.http.routers.backend-flexyte.tls: true
      traefik.http.routers.backend-flexyte.rule: (Host(`sample-restaurant.com`) || Host(`www.sample-restaurant.com`))  && PathPrefix(`/backendFlexyte/`)
    ports:
      - 3000:3000
    networks:
      - backend-flexyte
      
  mongodb-flexyte:
    image: mongo:latest
    container_name: mongodb-flexyte
    restart: unless-stopped
    ports:
      - 27017:27017
    labels:
      traefik.enable: true
      traefik.tcp.routers.mongo.rule: HostSNI(`sample-restaurant.com`)
      traefik.tcp.routers.mongo.entrypoints: mongo
      traefik.tcp.routers.mongo.service: mongo
      traefik.tcp.services.mongo.loadbalancer.server.port: 27017
      traefik.tcp.routers.mongo.tls.domains[0].main: sample-restaurant.com

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - backend-flexyte
    
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  backend-flexyte:
    external : true
