name: backend-flexyte

on :
  push :
    branches: ["main"]
  
jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: creating env variables
        run: |
          touch .env
          echo DB_URL=${{secrets.DB_URL}} >> .env
          echo MONGO_INITDB_ROOT_USERNAME=${{secrets.MONGO_INITDB_ROOT_USERNAME}} >> .env
          echo MONGO_INITDB_ROOT_PASSWORD=${{secrets.MONGO_INITDB_ROOT_PASSWORD}} >> .env
          echo ROOT_USER=${{secrets.ROOT_USER}} >> .env
          echo ROOT_USER_PASSWORD=${{secrets.ROOT_USER_PASSWORD}} >> .env
  
      - name: Publish Docker Image to GitHub Registry
        uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          image-name: backend-flexyte
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps: 
      - name: SSH Execute Commands
        uses: JimCronqvist/action-ssh@0.1.1
        with:
          hosts: ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          privateKey: ${{ secrets.SSH_KEY }}
          debug: false
          command: | 
            cd /projects/flexyte/backend-flexyte/
            docker login ghcr.io -u ${{ secrets.GIT_USERNAME }} -p ${{ secrets.GIT_TOKEN }}
            git remote set-url origin https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/FlorentKaram/backend-flexyte.git
            git pull
            docker stop backend-flexyte
            docker rm backend-flexyte
            docker image rm -f ghcr.io/florentkaram/backend-flexyte/backend-flexyte
            docker compose up -d